#!/bin/bash

mkdir _callirhoe
cp -r geom _callirhoe
cp -r holidays _callirhoe
cp -r lang _callirhoe
cp -r layouts _callirhoe
cp -r lib _callirhoe
cp -r style _callirhoe
cp callirhoe.py _callirhoe/__main__.py

cd _callirhoe
zip -q -r callirhoe.zip *
mv callirhoe.zip ../
cd ..
rm -rf _callirhoe
echo \#!/usr/bin/env python2 | cat - callirhoe.zip > callirhoe
chmod 755 callirhoe
rm callirhoe.zip

mkdir _calmagick

cp -r geom _calmagick
cp -r holidays _calmagick
cp -r lang _calmagick
cp -r layouts _calmagick
cp -r lib _calmagick
cp -r style _calmagick
cp callirhoe.py _calmagick
cp calmagick.py _calmagick/__main__.py

cd _calmagick
zip -q -r calmagick.zip *
mv calmagick.zip ../
cd ..
rm -rf _calmagick
echo \#!/usr/bin/env python2 | cat - calmagick.zip > calmagick
chmod 755 calmagick
rm calmagick.zip


